name: Continuous Deployment

on:
  workflow_run:
    workflows: [Docker]
    types:
      - completed
  workflow_dispatch:

env:
  KUBE_REPO: anthonyvouin/pec2-kube

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
    
    - name: Checkout Kubernetes repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.KUBE_REPO }}
        path: kube-files
        
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    - name: 'Setup Google Cloud CLI'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        install_components: 'gke-gcloud-auth-plugin'
        
    - name: 'Get GKE credentials'
      run: |
        gcloud container clusters get-credentials pec2  --region europe-west9 --project basic-tube-461312-r9
        
    - name: Apply Kubernetes configurations
      run: |

        # 1. supprimer les ressources existantes
        echo "Suppression des ressources existantes..."
        kubectl delete deployment back-pec-2-deployment || echo "Aucun déploiement trouvé ou erreur"
        
        # 2. Appliquer le Secret
        echo "Application des Secrets..."
        kubectl apply -f ./kube-files/kube/back-pec-2-config-secret.yaml || echo "Aucun fichier de secrets trouvé ou erreur"
        
        # 3. Appliquer la ConfigMap
        echo "Application de la ConfigMap..."
        kubectl apply -f ./kube-files/kube/back-pec-2-configmap.yaml || echo "Aucune ConfigMap trouvée ou erreur"
        
        # 4. Appliquer le Deployment
        echo "Application du Deployment..."
        kubectl apply -f ./kube-files/kube/back-pec-2-deployment.yaml
        
        # 5. Appliquer le Service
        echo "Application du Service..."
        kubectl apply -f ./kube-files/kube/back-pec-2-service.yaml || echo "Aucun Service trouvé ou erreur"
        
        # 6. Redémarrer le déploiement pour appliquer les dernières configurations
        echo "Redémarrage du déploiement..."
        kubectl rollout restart deployment/back-pec-2-deployment
    - name: Afficher les informations de déploiement
      run: |
        echo "Déploiement terminé!"
        echo "Statut des déploiements:"
        kubectl get deployment
        echo "Statut des services:"
        kubectl get service
        echo "Statut de l'ingress:"
        kubectl get ingress
        echo "Statut du certificat:"
        kubectl get managedcertificate